module.exports = {
	// search
	SEARCHING_ACCOUNTS: 'SEARCHING_ACCOUNTS',
	ACCOUNT_SEARCH_OK: 'ACCOUNT_SEARCH_OK',
	ACCOUNT_SEARCH_ERROR: 'ACCOUNT_SEARCH_ERROR',
	SORT_SEARCH_RESULTS: 'SORT_SEARCH_RESULTS',

	// edit
	FETCHING_ACCOUNT: 'FETCHING_ACCOUNT',
	ACCOUNT_FETCH_OK: 'ACCOUNT_FETCH_OK',
	ACCOUNT_FETCH_ERROR: 'ACCOUNT_FETCH_ERROR',
	ABANDON_EDIT: 'ABANDON_EDIT',
	SAVING_ACCOUNT: 'SAVING_ACCOUNT',
	ACCOUNT_SAVE_ERROR: 'ACCOUNT_SAVE_ERROR',
	ACCOUNT_SAVE_OK: 'ACCOUNT_SAVE_OK',

	// messages / errors
	CLOSE_MESSAGE: 'CLOSE_MESSAGE'
};
