module.exports = {
	SEARCH_ACCOUNTS: 'SEARCH_ACCOUNTS',
	ACCOUNT_SEARCH_RESULTS_OK: 'ACCOUNT_SEARCH_RESULTS_OK',
	ACCOUNT_SEARCH_RESULTS_ERROR: 'ACCOUNT_SEARCH_RESULTS_ERROR',
	SORT_SEARCH_RESULTS: 'SORT_SEARCH_RESULTS'
};
